apiVersion: v1
kind: Service
metadata:
  name: spring-apply2
spec:
  type: LoadBalancer
  ports: 
  - port: 80
    targetPort: 8082
    protocol: TCP
  selector: 
    app: spring-apply2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-apply2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-apply2
  template:
    metadata:
      labels:
        app: spring-apply2
    spec:
      containers:
      - name: webapp2
        image: wesoffiresis.azurecr.io/springboo-apply2:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-credential2